### PR TITLE
Added a simple way to convert between strings and integer

### PR DESCRIPTION
**Pull request by 1baga**
Added a simple way to convert an Integer to a string and vice versa. Useful when you are making quick conversions to be put in one line of code. Also added the modulus math operation.

screenshot from 2019-02-09 21-46-46

### CODE REVIEW

**Review by BolajiAyodeji — CHANGES_REQUESTED** [review]
Looks great!
You need to run some fixes first.
- Your Integer to String conversion doesn't seem to work, I get `34` instead of `"34"`
- You should use the camel case style to name your variables
`age_toString` should be `ageToString`
`length_toInt` should be `lengthToInt`

**Review by BolajiAyodeji — CHANGES_REQUESTED** [review]
Looks great!
Change the variable name from `modulus` to `findModulus`

**Comment by BolajiAyodeji** [comment]
> Looks great!
> Change the variable name from `modulus` to `findModulus`

You haven't made this change @1baga

**Comment by 1baga** [comment]
> > Looks great!
> > Change the variable name from `modulus` to `findModulus`
> 
> You haven't made this change @1baga

done

**Review by BolajiAyodeji — APPROVED** [review]
Looks great!
Thank you.

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @1baga for code

**Pull request merged**
